### ISSUE TITLE
Client does not reliably reconnect to broker

### ISSUE THREAD

**Issue by bblacey** [jonferreira/vera-mqtt#3]
If the client connection is severed by the broker, then the client will not reliably reconnect.  This is due to edge cases for the currently implemented connection state machine.  For example, in the current implementation, the client will not resume periodic mqtt pings via the MQTT.client.handler() method.

**Comment by bblacey** [comment]
Ok, I have looked into this issue and see more underlying problems.  We have two options, 1) on variable change, connect, send, disconnect/tear-down or 2) maintain persistent connection as the code attempts today.

Option 1 is super simple but will only support sending from the vera-mqtt plugin
Option 2 is a bit more complicated but doable.  Need to call handler() more frequently, on the order of 1/second and change the client KEEP_ALIVE time from 3600 to 60 seconds so the handler will send an mqtt PINGREQ to the broker every 60 seconds otherwise the broker will disconnect the client.

To preserve what's already here and leave the door open for someone in the future to add a subscription with a callback to process incoming MQTT messages on specific topics, I am going to implement Option 2.  If this were clean slate, I would probably just implement #1.

**Comment by jonferreira** [comment]
Great work @bblacey congrats!
